name: alh_calendar
description: A package for creating a custom calendar-widget.
  Builder-methods make it possible to design the calendar according to the given situation.
version: 0.0.1
repository: https://github.com/alhappler/alh_calendar

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl: ^0.19.0

flutter:


